### PR TITLE
Fixed issue with box of zero width or height

### PR DESCRIPTION
**Pull request by dobosevych**
### Issue:
```bash
 File "/Users/dobosevych/Documents/APPS/MLLab/surya/surya/input/processing.py", line 114, in slice_and_pad_poly
    cv2.fillPoly(mask, [np.int32(coordinates)], 1)
cv2.error: OpenCV(4.10.0) :-1: error: (-5:Bad argument) in function 'fillPoly'
> Overload resolution failed:
>  - Layout of the output array img is incompatible with cv::Mat
>  - Expected Ptr<cv::UMat> for argument 'img'
```
The issue was happening when mask had zero height or width, this was by bounding boxes of zero height of width.
### How to reproduce?
```python
from PIL import Image
import surya
from surya.ocr import run_ocr
from surya.model.detection.model import load_model as load_det_model, load_processor as load_det_processor
from surya.model.recognition.model import load_model as load_rec_model
from surya.model.recognition.processor import load_processor as load_rec_processor

image_paths = ["test1229.png"]

images = [Image.open(image_path) for image_path in image_paths]
langs = ["ru"]  # Replace with your languages - optional but recommended
det_processor, det_model = load_det_processor(), load_det_model()
rec_model, rec_processor = load_rec_model(), load_rec_processor()

predictions = run_ocr(images, [langs] * len(images), det_model, det_processor, rec_model, rec_processor)
print(predictions)
```
test1229

### Solution:
Added additional filtering to support such cases in clean_contained_boxes,  also function renamed to clean_boxes, as not it not only clean contained boxes, but filters zero width boxes.

I have read the CLA Document and I hereby sign the CLA

### CODE REVIEW

**Comment by dobosevych** [comment]
recheck

**Comment by dobosevych** [comment]
recheck

**Comment by dobosevych** [comment]
I have read the CLA Document and I hereby sign the CLA
recheck

**Comment by dobosevych** [comment]
recheck

**Comment by VikParuchuri** [comment]
Thanks for the fix!

**Pull request merged**
